### ISSUE TITLE
Media Creation Tool wiki page missing from repo

### ISSUE THREAD

**Issue by sthivaios** [Microsoft-community/Community-website#163]
Btw, label : bug

Small issue I noticed while working on PR #162 :

In the wiki's index.md file, the "Using the media creation tool" page links to "using-the-media-creation-tool.md" file, **however** it seems to have been renamed to "downloading-windows.md" and the "Using the media creation tool" does in fact redirect to "downloading-windows.md" on https://msft.chat, so someone probably just accidentally rolled back a commit?

I'm opening this bug instead of a PR with a fix because it would conflict with #162. If someone wants to fix this sure, otherwise I'll make a lil PR when 162 is merged.

**Comment by FloatingMilkshake** [comment]
The redirect appears to be configured [here](https://github.com/Microsoft-community/Community-website/blob/master/.vuepress/public/_redirects) which leads me to believe this was intentional. Paging @Erisa as she seems to be the one who configured them.

**Comment by sthivaios** [comment]
@FloatingMilkshake 

closing this because erisa seems to have done that on purpose

01660189429817e923d940d7873e011ec0353898

**Comment by FloatingMilkshake** [comment]
That was my thinking too, thank you for noticing though

**Comment by Erisa** [comment]
The redirect is so that old links don't break, the links can still be updated to remove the extra redirect step where needed
