### ISSUE TITLE
Remaster the wiki entries in chronological order as Acto said

### ISSUE THREAD

**Issue by julsehn** [Microsoft-community/Community-website#203]
Order them in chronological order

**Comment by julsehn** [comment]
@waitwhatActo What about to do a dropdown in the slide bar like powertoys? https://discord.com/channels/150662382874525696/836727934172659732/1303792194724954113

**Comment by waitwhatActo** [comment]
> @waitwhatActo What about to do a dropdown in the slide bar like powertoys? https://discord.com/channels/150662382874525696/836727934172659732/1303792194724954113

I mean personally I don't think categorizing it here is necessary
unless if you have an idea on how we should categorize it

**Comment by julsehn** [comment]
> > @waitwhatActo What about to do a dropdown in the slide bar like powertoys? https://discord.com/channels/150662382874525696/836727934172659732/1303792194724954113
> 
> I mean personally I don't think categorizing it here is necessary unless if you have an idea on how we should categorize it
This is my idea @waitwhatActo 
Home
Troubleshooting
- Fixing problems Microsoft store
- Troubleshooting
- Getting Live Support for Hacked Accounts
Installation:
- Downloading Windows
- Installing Windows
- Create a Bootable USB Using Ventoy
- Reinstalling GPU Drivers
- Installing and Updating Drivers
Protection and/or tips:
- Windows tips
- The Windows Feature Store
- Joining and Leaving the Windows Insider Program
- Common Windows Misconceptions
- Backing Up Data
- Windows Keyboard Shortcuts
Miscelanus or offtopic:
- Desktop & Mobile Wallpapers
