### ISSUE TITLE
Add "how to become a mod" section within members documentation

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Community-website#31]
application link which should be included within that section https://go.msft.chat/mod-application

**Comment by Danielx64** [comment]
Are you looking for a simple Q&A being added or a whole new section? If Q&A, I just wrote something simple up and made a pull request. If a new section, feel free to let me know of the details needed

**Comment by Jasius** [comment]
I didn't have a specific idea in mind, just wanted to have a section which would mention that.
