### ISSUE TITLE
Implement OAuth2 for ban appeals page

### ISSUE THREAD

**Issue by sylveon** [Microsoft-community/Community-website#43]
This would provide undeniable proof of identity, and reduce spam. Currently, the username is a text field which means people can put in fake appeals (like how it recently happened).

**Comment by sylveon** [comment]
Optionally, could also check the user against the server banlist to see if they're truly actually banned.

**Comment by sylveon** [comment]
ez: https://github.com/sylveon/discord-ban-appeals

**Comment by Danielx64** [comment]
Nice one, when will it be ready for testing?

Sent from Nine
________________________________

**Comment by sylveon** [comment]
Well [it already works](https://discord-ban-appeal-preview.netlify.app/), it would just need to be integrated with our existing website.

I'm doing this for a (to-be-announced) project with Discord T&S though so integrating it here will have to wait, or somebody can pick up the task and do it.

**Comment by Danielx64** [comment]
Well I just did a test one via my phone and it works great.

Only thing, if you edit the string on the end of the URL and submit the form, it doesn't display a friendly message otherwise I like it

**Comment by sylveon** [comment]
That's still a thing to be worked on but I'm not sure we should account for users shooting themselves in the foot.

**Comment by Danielx64** [comment]
Now that I can see how easy it is to setup, I'm happy to have a go at getting this setup. By the looks of this, it would need to go under it own sub domain like appeal.msft.chat?

Also could this server have it own custom version so that it can match up with the rest of the site or no point?

**Comment by Erisa** [comment]
It seems this issue was forgotten, I implemented this some time ago as a fork of sylveons work ([Microsoft-community/discord-ban-appeals](https://github.com/Microsoft-community/discord-ban-appeals)) and the link on this site was updated accordingly.

Thanks for the suggestion!
