### ISSUE TITLE
Regression: Sections jumplist doesn't work

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Community-website#57]
Direct links to section such as this one https://msft.chat/member/#channels-and-their-use do not seem to work, jumping between sections within the page works as intended but giving a direct link to certain section seems to just load page is if no section is selected.

**Comment by Danielx64** [comment]
Hmmm, are you talking about the links in the sidebar not being selected? I just used the link above in a new private window and it goes to the section but the link in the sidebar is not highlighted.

**Comment by Jasius** [comment]
I recorded a small clip, you can see that appropriate section doesn't get opened initially 
https://streamable.com/toy2q0 @Danielx64

**Comment by Jasius** [comment]
It does seem to work fine on Firefox, I suppose this is a Chromium bug of some sort.

**Comment by Danielx64** [comment]
Yep, I just tested in Edge (I was using firefox before) and I can reproduce this

**Comment by Jasius** [comment]
Im fairly certain that it worked in the past on Chromium browsers too.

**Comment by Erisa** [comment]
Resolved by #150
