### ISSUE TITLE
Outdated roles section within mods documentation

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Community-website#58]
> Windows insiders are still old names, there have been extra roles such as minecraft champion, coffee club, windows insiders release preview been created since last updated.

**Comment by Jasius** [comment]
@Danielx64 this might interest you

**Comment by Danielx64** [comment]
Feel free to assign this to me @Jasius

**Comment by Danielx64** [comment]
On my phone, I was able to get a list of every single role, did you want all the bots (MEE6 for example) and other Microsoft ones added?

![Screenshot_20200810-134412](https://user-images.githubusercontent.com/289220/89881849-5eb5a380-dc09-11ea-85a8-c35a99b90367.png)
![Screenshot_20200810-134418](https://user-images.githubusercontent.com/289220/89881853-5fe6d080-dc09-11ea-9cdc-2d6b10fe231a.png)
![Screenshot_20200810-134425](https://user-images.githubusercontent.com/289220/89881858-6117fd80-dc09-11ea-8506-9264e3fc2258.png)
![Screenshot_20200810-134431](https://user-images.githubusercontent.com/289220/89881861-61b09400-dc09-11ea-9645-351fc09112da.png)
![Screenshot_20200810-134347](https://user-images.githubusercontent.com/289220/89881862-62492a80-dc09-11ea-9798-17e28e1b89e6.png)
![Screenshot_20200810-134353](https://user-images.githubusercontent.com/289220/89881865-62e1c100-dc09-11ea-95bd-4f8ae7c7eb6e.png)
![Screenshot_20200810-134400](https://user-images.githubusercontent.com/289220/89881868-637a5780-dc09-11ea-9b81-abb257ee08e5.png)
![Screenshot_20200810-134405](https://user-images.githubusercontent.com/289220/89881870-6412ee00-dc09-11ea-825b-cb9cde8d593d.png)

**Comment by Jasius** [comment]
Bot roles aren't important, as for "Microsoft ones" I am not entirely sure what you mean by that.

**Comment by Danielx64** [comment]
I mean the Datacentre Wizard, Azure Data Wizard, Edge Community Manager etc

**Comment by Jasius** [comment]
> I mean the Datacentre Wizard, Azure Data Wizard, Edge Community Manager etc

Oh, those. It's okay to exclude them as they're super specific and most likely list of them will grow over time.

**Comment by Jasius** [comment]
Completed in #59
