### ISSUE TITLE
Implement OAuth2 for the mod application form 

### ISSUE THREAD

**Issue by Danielx64** [Microsoft-community/Community-website#61]
This is more of a spin-off of https://github.com/Microsoft-community/Community-website/issues/43, the only other advantage (other than spam preventions and misleading mod applications) is that the style can be matched up with the rest of the site (light and dark themes).

**Comment by Danielx64** [comment]
The other option is to convert the page at https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAMAALRLLfZUMERaWlBPTllUOEZSSUcyTU1IUkc4UDJSTC4u to like the current ban appeal page

**Comment by Jasius** [comment]
This is not going to be done as per reasons mentioned in #62
